### ISSUE TITLE
How push node to Forget stake address? 

### ISSUE THREAD

**Issue by minzak** [HorizenOfficial/nodetracker#100]
How long Node must be shut down before it can be possible to recreate it and use the stake address?

I have misconfigured some nodes, where it can`t be run. because I got error:
```
2020-09-02 11:40:44 UTC -- Waiting to register
2020-09-02 11:40:44 UTC -- Registration failed. Staking address already registered. znTWq8CdQvpHfomKbjeJH7CoDytusCeLFE3
2020-09-02 11:41:43 UTC -- Unable to collect stats without a nodeid.
```
Before node was offline, and node tracker forget about this node (absent record)
But try to use in new node old stake address - got the same error.
How to refresh a new node with an old stake address?
```
znWQmcHmy44mpSQeVpqaLt3wuYse7XufPEA
znTWq8CdQvpHfomKbjeJH7CoDytusCeLFE3
```
Thanks.

Or how to get the needed configuration to recreate the old node?
P.S. use API for get several records and recreate with new t-address without ID = is no lucky way.

**Comment by uanl979** [comment]
Hi there @bizlevel 

Old, inactive (dead) nodes will take 30 days until the tracking system removes their registration data.

    After 5 days of downtime and 5 days of inactivity consecutively, the node's status will change to "Zombie"
    Zombie nodes may be revived thereafter for a 20 day period before it gets automatically removed from the tracker

After a node has been removed, the following registration details will be made available to be used on new node registrations

    IPV4/IPV6 addresses
    Fully Qualified Domain Names (FQDNs)
    Node t-address (wallet.dat on the node)
    Staking address

If you have further doubts you, a better place to raise any issue is on our support system. Please raise a ticket if needed :)

[support.horizen.io](https://horizenofficial.atlassian.net/servicedesk/customer/portals)

**Comment by minzak** [comment]
Hm, it is means, that when I use API after 30 days I must find nothing about the needed node?
To recreate it, But I curl today and got data near 60 days ago and also near a year ago!

```curl -s "https://securenodes3.na.zensystem.io/api/nodes/my/list?key=$API_KEY&addr=1" ```
with result:

    {
      "id": 349633597,
      "status": "dead",
      "home": "ts1.na",
      "curserver": "ts1.na",
      "ip4": null,
      "ip6": "2001:470:1f0a:5XXXX",
      "fqdn": "872-z.dyn.XXXXX",
      "createdAt": "2019-11-22T05:27:12.000Z",
      "updatedAt": "2019-12-31T01:15:11.000Z",
      "stkaddr": "znWQmcHmy44mpSQeVXXXXXX",
      "taddr": "znkt7NV9TggF7dko7MSXXXXXXX",
      "email": "siaXXXX@gmail.com",
      "category": "none",
      "zenver": 2001950,
      "trkver": "0.4.0"
    },

    {
      "id": 349694599,
      "status": "dead",
      "home": "ts1.na",
      "curserver": "ts1.na",
      "ip4": null,
      "ip6": "2001:470:1f0a:XXX",
      "fqdn": "872-z.dyn.XXX",
      "createdAt": "2020-02-04T18:18:49.000Z",
      "updatedAt": "2020-08-13T11:06:45.000Z",
      "stkaddr": "znWQmcHmy44mpSQeXXXX",
      "taddr": "znm6wqoYwngqouxTDkXXXX",
      "email": "siaXXXX@gmail.com",
      "category": "vm-dcg-zch10",
      "zenver": 2002151,
      "trkver": "0.4.0"
    },

And it is still imposible to reuse the STAKE address because it is still in DB.

**Comment by ADumaine** [comment]
Hi minzak,

Node data is not deleted, so yes you are able to access dead nodes via the API.  Dead nodes are ignored during a new node registration, allowing a stake address to be re-used.

It looks like the node finally registered or the issue you are having trying to register another node is because the stake address `znWQmcHmy44mpSQeXXXX`  is already being used by node 349771753  and not the dead nodes.   It was created 2020-10-07 09:59:15 and is currently up.

**Comment by minzak** [comment]
Yes, needs more time to wait, and now it is worked.
