### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by minzak** [HorizenOfficial/nodetracker#104]
On https://securenodes1.na.zensystem.io/nodes/mynodes - I can see this error:

`unable to verify the first certificate`

Ок, I renew to one next from here:
https://www.ssl2buy.com/wiki/alphassl-intermediate-root-ca-certificates
https://letsencrypt.org/ru/certificates/ (https://letsencrypt.org/certs/trustid-x3-root.pem.txt) 

Fully redeploy Node and nothing (
Still the same error. What is wrong?
How to eliminate its error?

It is can be related to https://github.com/HorizenOfficial/zen/issues/76

**Comment by ADumaine** [comment]
For anyone finding this later:  zend needs to be restarted after refreshing or changing the ssl cert.
It may be helpful to call a script from certbot after a succesful cert update to restart the zend process. 

This may also have been an issue with intermediate certs not being installed or not updating properly.
Here is an example of how to fix when using letsencrypt: https://zen-solutions.io/how-to-fix-r3-expired-lets-encrypt-certificates-on-nodes/
