### ISSUE TITLE
Node.js 10.x is no longer actively supported!

### ISSUE THREAD

**Issue by fisherwei** [HorizenOfficial/nodetracker#106]
================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 10.x is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium"
   * https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium" (recommended)
   * https://deb.nodesource.com/setup_16.x — Node.js 16 "Gallium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

please update and test to newer node.js LTS version.

**Comment by ADumaine** [comment]
The docs are just outdated.  I am not sure when they will be updated.

Node 16.x or other LTS work fine.

https://github.com/HorizenOfficial/nodetracker/issues/102#issuecomment-730496065
