### ISSUE TITLE
Secure Node will not recover from exception after migrated to new host

### ISSUE THREAD

**Issue by nscmcgrath** [HorizenOfficial/nodetracker#93]
After migrating one of my secure nodes to a new host, an exception relevant to the previous host will not clear, leaving the node in a down state when it should be in an up state.

The node can be found here: https://securenodes1.na.zensystem.io/nodes/349698361/detail

Details:
- Original node was running in parallel on the same device as another node, collisions on port 9033 were happening so the node needed to be moved to a standalone host
- Node was moved to a standalone host. This was done by cloning another secure node I own, changing the wallet.dat to the previous node and copyting everything from nodetracker/config to the new host.
- New node comes up and runs fine, but old exception regarding IPv6 address conflicts are staying.

**Comment by psyraxaus** [comment]
You may have multiple IPv6 addresses on your network interface.  The tracker uses Socket.io and will use any available outbound IP address.  What is recommended is that you limit your instance to a single IPv6 address, use that IP address in the externalip= value, and the tracker will connect out of that IP address

**Comment by nscmcgrath** [comment]
@psyraxaus I migrated my node away from a device containing multiple IPv6 addresses to a linode due to the network configuration being dynamic and I didn't want to go through the hassle of making it static.

Original node interface:
`$ ifconfig enp12s0
enp12s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.228  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 fe80::25e0:8724:1fbc:ee47  prefixlen 64  scopeid 0x20<link>
        inet6 2601:646:8680:1e31:d1f3:5ed8:6789:acb8  prefixlen 64  scopeid 0x0<global>
        inet6 2601:646:8680:1e31:181b:1a1d:bd1c:a93d  prefixlen 64  scopeid 0x0<global>
        inet6 2601:646:8680:1e31:2c98:b116:ae8e:d295  prefixlen 64  scopeid 0x0<global>
        inet6 2601:646:8680:1e31:43ea:2f04:4f61:e2b7  prefixlen 64  scopeid 0x0<global>
        inet6 2601:646:8680:1e31:2d07:7a54:7833:5106  prefixlen 64  scopeid 0x0<global>
        inet6 2601:646:8680:1e31:ad15:44e3:ecce:d4a3  prefixlen 128  scopeid 0x0<global>
        inet6 2601:646:8680:1e31:2078:3f76:8d31:fba1  prefixlen 64  scopeid 0x0<global>
        ether d0:50:99:52:f3:89  txqueuelen 1000  (Ethernet)
        RX packets 69254980  bytes 27143941579 (27.1 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 98810772  bytes 88152592566 (88.1 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xfb400000-fb47ffff  
`
New node interface (linode):
`$ ifconfig eth0
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 45.33.104.210  netmask 255.255.255.0  broadcast 45.33.104.255
        inet6 fe80::f03c:92ff:fe24:e1a9  prefixlen 64  scopeid 0x20<link>
        inet6 2600:3c01::f03c:92ff:fe24:e1a9  prefixlen 64  scopeid 0x0<global>
        ether f2:3c:92:24:e1:a9  txqueuelen 1000  (Ethernet)
        RX packets 28338  bytes 9566283 (9.5 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 17182  bytes 2885003 (2.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

**Comment by psyraxaus** [comment]
Ok so you might still have some old config in the zen.conf.

Please have a look at the zen.conf for externalip= entries and make sure that you only have the Single ipv6 address of the new instance and no others

**Comment by nscmcgrath** [comment]
It does not contain the old entries

**zen.conf**
```$ cat ~/.zen/zen.conf 
rpcuser=<omit>
rpcpassword=<omit>
rpcport=18231
rpcallowip=127.0.0.1
rpcworkqueue=512
server=1
daemon=1
listen=1
txindex=1
logtimestamps=1
### testnet config
#testnet=1
tlscertpath=/etc/letsencrypt/live/sn1.colinaws.com/cert.pem
tlskeypath=/etc/letsencrypt/live/sn1.colinaws.com/privkey.pem
externalip=2600:3c01::f03c:92ff:fe24:e1a9
port=9033
```

**Comment by psyraxaus** [comment]
Can you please lodge a support ticket through https://support.horizen.global 

And we will get the developers to look at the server side entries for your node

**Comment by uanl979** [comment]
I will be closing this issue, since this has been funneled to our Helpdesk. Thanks all :)
