### ISSUE TITLE
Secure node is false after recovered from dead

### ISSUE THREAD

**Issue by RakibFiha** [HorizenOfficial/nodetracker#94]
A node was recovered from dead but it is still showing up on the tracker as down, though dead node should not be showing up in the tracker at all. As a result, the real recovered node (349711723) is showing false in the tracker.

**Supposed to be dead but still shows up:** (A) https://securenodes2.na.zensystem.io/nodes/349602133/detail

**The recovered node:** (B)
https://securenodes2.na.zensystem.io/nodes/349711723/detail

Details:
A (349602133) was dead, when it was recovered and after recovery newly assigned id was B (349711723). But, after recovery A somehow was registered again in the tracker along with B.

**Comment by RakibFiha** [comment]
This issue was resolved via a ticket to the support.

**Comment by RakibFiha** [comment]
This issue has occurred to me again when I tried to recover a dead node.

https://securenodes2.na.zensystem.io/nodes/327614/detail

Which should not have been registered as its dead. But it mysteriously reappeared in the tracker. Now, if I remove nodeid from config.json and try to run zentracker it says: 
`Registration failed. Staking address already registered.
`and if I use old nodeid it says:
`Too many configuration values changed at once. Reconnect not allowed. Only change one at a time.`
More details at discord:
https://discordapp.com/channels/334085157441110017/364105464348278794/697662659457449985

**Comment by psyraxaus** [comment]
Hello @RakibFiha,
I can see that the reopened issue has been resolved and your last linked node is up again and in compliance.

I will close out this issue now, please reach out again in the future if you have any further issues.

Kind regards
