### ISSUE TITLE
How to change several node values at one?

### ISSUE THREAD

**Issue by bizlevel** [HorizenOfficial/nodetracker#99]
For example, I need to migrate from one server to another one.
How to do it?
Because we got a message like this:
**`Too many configuration values changed at once. Reconnect not allowed. Only change one at a time.`**

I have main params like this:
```
cat container.conf
    ZEND_EXTERNALIP=2001:470:xx:xx::2460
    ZEND_PORT=9033
    ZEND_ONLYNET=ipv6
    SSLCERT_KEY=bundle.pem
    SSLCERT_CERT=bundle.pem
    NDT_STAKE_ADDR=znZinRPDxxxxxxxxxxxxx
    NDT_EMAIL=xxxxxx@gmail.com
    NDT_FQDN=170-z.xxxxxxxx.io
    NDT_IPV=6
    NDT_REGION=NA
    NDT_HOME=ts1.na
    NDT_NID=349695175
    NDT_CATEGORY=vm-xxxx-xxx
```
And of course, I can change on the same node, not important value like this - NDT_CATEGORY or NDT_HOME, after node work sometimes with these changes, I must change for example ZEND_EXTERNALIP for migrating!

But I still got the message: 
**`Too many configuration values changed at once. Reconnect not allowed. Only change one at a time.`**

But I changed only ONE parameter!!!
How it can be?

All these changes was made on 349695175 node, and still no luck!

How to migrate?
Thanks.

**Comment by cronicc** [comment]
There are three values checked, only one of the three is allowed to change at a time.
1. Node t-address
2. Node stake address
3. Node Primary IP address (IPv4 or IPv6)

Node t-address is not covered in any of the configuration files, but actually is the first transparent address in the node's wallet.dat (`zen-cli listaddresses | head -n1`). I suspect that you didn't copy wallet.dat when you migrated servers.

**Comment by bizlevel** [comment]
At last, I found, we have several addresses.
And your example cut only one first, but wallet can have several addresses, and just need to check to use the same address.
